# Generated by Django 5.0.4 on 2024-05-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateuser",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
